version: '3.8'

services:
  secure-rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secure_rag_service
    ports:
      - "8501:8501"
    environment:
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5:3b
      - CHUNK_SIZE=500
      - CHUNK_OVERLAP=50
      - RRF_K=60
    volumes:
      - ./storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
